import "server-only";

import { prisma } from "@/lib/db/prisma";
import { calculateHealth } from "@/lib/health/score";
import { resend } from "@/lib/resend";
import { clientEnv } from "@/lib/env";
import { createNotification } from "@/lib/notifications";

const DEDUP_WINDOW_MS = 7 * 24 * 60 * 60 * 1000; // 7 days
const PATCH_AGE_THRESHOLD = 30; // days

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface AlertCheckResult {
  sent: number;
  errors: string[];
}

// ---------------------------------------------------------------------------
// Deduplication
// ---------------------------------------------------------------------------

async function isDeduped(
  organizationId: string,
  entityType: string,
  entityId: string,
  alertType: string,
): Promise<boolean> {
  const cutoff = new Date(Date.now() - DEDUP_WINDOW_MS);
  const existing = await prisma.alertLog.findFirst({
    where: { organizationId, entityType, entityId, alertType, sentAt: { gte: cutoff } },
    select: { id: true },
  });
  return existing !== null;
}

async function recordAlert(
  organizationId: string,
  entityType: string,
  entityId: string,
  alertType: string,
): Promise<void> {
  await prisma.alertLog.create({
    data: { organizationId, entityType, entityId, alertType },
  });
}

// ---------------------------------------------------------------------------
// Email helpers
// ---------------------------------------------------------------------------

function alertEmailHtml(body: string): string {
  return `<!DOCTYPE html>
<html>
<body style="font-family:sans-serif;max-width:600px;margin:0 auto;padding:24px;color:#1e293b;">
  ${body}
  <hr style="margin:24px 0;border:none;border-top:1px solid #e2e8f0;" />
  <p style="font-size:12px;color:#94a3b8;">Generated by ClientPulse</p>
</body>
</html>`;
}

// ---------------------------------------------------------------------------
// Main export
// ---------------------------------------------------------------------------

export async function checkAndSendAlerts(): Promise<AlertCheckResult> {
  const errors: string[] = [];
  let sent = 0;

  const orgs = await prisma.organization.findMany({
    select: {
      id: true,
      name: true,
      users: {
        where: { role: "OWNER" },
        select: { email: true },
        take: 1,
      },
      clients: {
        select: {
          id: true,
          name: true,
          devices: {
            select: {
              id: true,
              hostname: true,
              patchAgeDays: true,
              lastSeen: true,
            },
          },
        },
      },
    },
  });

  for (const org of orgs) {
    const ownerEmail = org.users[0]?.email;
    if (!ownerEmail) continue;

    for (const client of org.clients) {
      const clientUrl = `${clientEnv.NEXT_PUBLIC_SITE_URL}/clients/${client.id}`;

      // --- patch_age alert: one alert per device over the threshold ---
      for (const device of client.devices) {
        if (device.patchAgeDays <= PATCH_AGE_THRESHOLD) continue;

        const alreadySent = await isDeduped(
          org.id,
          "device",
          device.id,
          "patch_age",
        );
        if (alreadySent) continue;

        try {
          await resend.emails.send({
            from: "ClientPulse <alerts@clientpulse.app>",
            to: ownerEmail,
            subject: `ClientPulse Alert — Patch age exceeded for ${device.hostname}`,
            html: alertEmailHtml(`
              <h2 style="margin-top:0;">⚠️ Patch Age Alert</h2>
              <p><strong>Client:</strong> ${client.name}</p>
              <p><strong>Device:</strong> ${device.hostname}</p>
              <p><strong>Patch age:</strong> ${device.patchAgeDays} days
                 <span style="color:#ef4444;">(threshold: ${PATCH_AGE_THRESHOLD} days)</span></p>
              <p>This device has not been patched within the expected window.
                 Please review and apply updates.</p>
              <p><a href="${clientUrl}" style="color:#6366f1;">View client in ClientPulse →</a></p>
            `),
          });

          await recordAlert(org.id, "device", device.id, "patch_age");
          await createNotification(
            org.id,
            "Patch Age Alert",
            `${device.hostname} (${client.name}) has not been patched in ${device.patchAgeDays} days.`,
            `${clientEnv.NEXT_PUBLIC_SITE_URL}/clients/${client.id}`,
          );
          sent++;
        } catch (err) {
          errors.push(
            `patch_age alert for device ${device.id} (${device.hostname}): ${String(err)}`,
          );
        }
      }

      // --- health_critical alert: one alert per client in CRITICAL band ---
      const health = calculateHealth({
        deviceCount: client.devices.length,
        devices: client.devices.map((d) => ({
          patchAgeDays: d.patchAgeDays,
          lastSeen: d.lastSeen,
        })),
      });

      if (health.band !== "CRITICAL") continue;

      const alreadySent = await isDeduped(
        org.id,
        "client",
        client.id,
        "health_critical",
      );
      if (alreadySent) continue;

      try {
        await resend.emails.send({
          from: "ClientPulse <alerts@clientpulse.app>",
          to: ownerEmail,
          subject: `ClientPulse Alert — ${client.name} health is CRITICAL`,
          html: alertEmailHtml(`
            <h2 style="margin-top:0;">🔴 Critical Health Alert</h2>
            <p><strong>Client:</strong> ${client.name}</p>
            <p><strong>Health score:</strong>
               <span style="color:#ef4444;font-weight:bold;">${health.score} — CRITICAL</span></p>
            <p>This client's health has dropped to the Critical band.
               Immediate attention is required.</p>
            <p><a href="${clientUrl}" style="color:#6366f1;">View client in ClientPulse →</a></p>
          `),
        });

        await recordAlert(org.id, "client", client.id, "health_critical");
        await createNotification(
          org.id,
          "Critical Health Alert",
          `${client.name} health score dropped to CRITICAL (${health.score}).`,
          `${clientEnv.NEXT_PUBLIC_SITE_URL}/clients/${client.id}`,
        );
        sent++;
      } catch (err) {
        errors.push(
          `health_critical alert for client ${client.id} (${client.name}): ${String(err)}`,
        );
      }
    }
  }

  return { sent, errors };
}
